name: najim-backend
services:
    najim-backend-dev:
        build: .
        env_file:
            - .env
        ports:
            - 2222:22
            - 9092:8080
        volumes:
            - ./models:/app/models
        restart: unless-stopped